### ISSUE TITLE
Extend default resource types.

### ISSUE THREAD

**Issue by ellavas** [SAP/scimono#100]
Hello,

I want to add a schema extension to the user resource. 
As described in the RFC 7644, the resource type should be enhanced with the extensions. 

Example from RFC 7644

```
{
    "totalResults":2,
    "itemsPerPage":10,
    "startIndex":1,
    "schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],
    "Resources":[{
      "schemas": ["urn:ietf:params:scim:schemas:core:2.0:ResourceType"],
      "id":"User",
      "name":"User",
      "endpoint": "/Users",
      "description": "User Account",
      "schema": "urn:ietf:params:scim:schemas:core:2.0:User",
      "schemaExtensions": [{
        "schema":
          "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
        "required": true
      }],
      "meta": {
        "location":"https://example.com/v2/ResourceTypes/User",
        "resourceType": "ResourceType"
      }
    },
   {
     "schemas": ["urn:ietf:params:scim:schemas:core:2.0:ResourceType"],
     "id":"Group",
     "name":"Group",
     "endpoint": "/Groups",
     "description": "Group",
     "schema": "urn:ietf:params:scim:schemas:core:2.0:Group",
     "meta": {
       "location":"https://example.com/v2/ResourceTypes/Group",
       "resourceType": "ResourceType"
     }
   }]
  }

```

In the scimono library, it's possible to extend the default resource types with custom types but I don't find any solution to modify an existing resource. 
Do you have any suggestion ?

Many thanks

**Comment by karaimin** [comment]
Hi @ellavas 

Currently...: 
1. `/ResourceTypes` endpoint returns fixed values for core resource types (User, Group, Schema). 
2. You can create your own custom schema (via `/Schemas` endpoint) and use it for both User and Group in CRUD operations.

**Comment by ellavas** [comment]
Hello @karaimin,

I have already created my custom schema and it works fine in CRUD operations. 
But I want to make this extension required for the User resource as defined in the RFC below:
```
"schemaExtensions": [{
        "schema":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
        "required": true
 }]
```
This should allow to have resource types properly defined and to return a bad request (validation error) when the extension is missing in the body.

Do you plan to provide such feature ?

Best regards

**Comment by karaimin** [comment]
Hi @ellavas 
We haven't discussed such feature. Now, we have other tasks with higher priority. But, we will accept feature requests and will be glad to accept and discuss contributions. 
So, If such feature is critical for you, feel free to open Pull Request with contribution to the code base :) 
Best regards
Aleydin

**Comment by ellavas** [comment]
Hi @karaimin, 

I've created a pull request to support this feature. 
I'm open to any feedback

Thanks

**Comment by karaimin** [comment]
Hi @ellavas 
New version of scimono (0.0.15) was released today
Regards

**Comment by ellavas** [comment]
Hi @karaimin,

Thanks for the release.
