### ISSUE TITLE
Create user with password

### ISSUE THREAD

**Issue by henrikpalsson** [SAP/scimono#137]
Should it not be possible to create or update a user with password?
I can only find a way to set the password thru the patch command.
This happen during a upgrade to 0.0.24 from 0.0.7.

**Comment by karaimin** [comment]
Hi @henrikpalsson.
If you are using password property on the client side - (e.g you want to create User and send it to the server), you are free to do it. There is `User.Builder` method `setPassword`

**Comment by henrikpalsson** [comment]
I have done that and if I debug the client side I see the password is set but when it arrives in _createUser_ in class _Users_ the password is null. I think Json is not setting it in class _User_, because the input parameter password in the constructor is null.

**Comment by karaimin** [comment]
Can you check on the client side whether it is properly serialized into JSON. 
By default password property is not serializable (Server is prohibited to expose password outside)
On the client side, if you use the default settings for creating `ScimClientService` (not `fromPreconfiguredWebTarget()`), it  use `ClientJacksonResolver` which is responsible for enabling this feature.

If you use the second approach - `fromPreconfiguredWebTarget()`. You can explicitly register it in the client config.

- if you use Jersey - `new org.glassfish.jersey.client.ClientConfig().register(ClientJacksonResolver.class)`

**Comment by henrikpalsson** [comment]
Thanks for that information but in this case I am using a junit so the client is then Rest-assured. I need to figure out how I add that object mapper. To you have a clue?

**Comment by henrikpalsson** [comment]
Got it to work when added this:
`io.restassured.mapper.ObjectMapper objectMapper = new Jackson2Mapper(((type, charset) -> {
            return new ClientJacksonResolver(false).getContext(resourceClass);
        }));
        restAssured.objectMapper(objectMapper);`
Thanks!
