### ISSUE TITLE
getRequredSchemas only fetch custom schemas

### ISSUE THREAD

**Issue by henrikpalsson** [SAP/scimono#49]
Why does getRequredSchemas in PathValidationFramework only getCustomSchemas?
I try do change a attribute on a User from the core User schema but I can't get it work and I think it is because this function only handles custom schemas.

**Comment by karaimin** [comment]
@henrikpalsson The problem should be fixed now and will be available in next release version

**Comment by henrikpalsson** [comment]
Thanks @karaimin for a fast fix. Do you now when you will release the next version?

**Comment by karaimin** [comment]
@henrikpalsson version 0.0.6 is released now.

**Comment by henrikpalsson** [comment]
I find version 0.0.6 on MVNrepo but the files don't exists. https://repo1.maven.org/maven2/com/sap/scimono/scimono-server/0.0.6/scimono-server-0.0.6.jar

**Comment by karaimin** [comment]
@henrikpalsson Which file are you looking for. In `PatchValidationFramework` `getRequiredSchemas()` method was edited.

**Comment by henrikpalsson** [comment]
It is working now.
