### ISSUE TITLE
ExceptionMappers does not set mediaType

### ISSUE THREAD

**Issue by henrikpalsson** [SAP/scimono#53]
I had problem with exceptions. I got this return when I for example enter wrong endpoint, _"No message body writer has been found for class com.sap.scimono.entity.ErrorResponse, ContentType: */*"_. I also got it when I entered wrong data in the body for a POST. I found out that if I sent the MediaType in the exceptionMappers I got the right ErrorRespons encoded correct.

The return statement look like this after my change, _" return Response.fromResponse(exception.getResponse()).entity(scimError).type(new MediaType("application", "scim+json")).build();"_

Have I done something wrong I my usage of the API? Or is this a bug?

**Comment by VladislavStefanov** [comment]
Can you give more details on how to reproduce this problem? In what way is the data in the body for the POST request wrong? By wrong endpoint what do you mean? Is this message in the response body: 
> "No message body writer has been found for class com.sap.scimono.entity.ErrorResponse, ContentType: /"

What is the whole response?

**Comment by henrikpalsson** [comment]
This is a screen dump from my test with wrong endpoint, using Group instead of Groups
<img width="823" alt="Skärmavbild 2020-02-12 kl  15 16 19" src="https://user-images.githubusercontent.com/59912567/74343220-02cda780-4dab-11ea-9fa2-c786dc0d617f.png">

**Comment by VladislavStefanov** [comment]
Can you show the headers of the request too?

**Comment by henrikpalsson** [comment]
I have tested both with content-type set and without. Same result.
<img width="839" alt="Skärmavbild 2020-02-12 kl  15 35 41" src="https://user-images.githubusercontent.com/59912567/74344748-55a85e80-4dad-11ea-97aa-4c699c853aae.png">

**Comment by VladislavStefanov** [comment]
Have you tried with Content-Type: application/scim+json?
Here scim and json are reversed.

**Comment by henrikpalsson** [comment]
Yes I tested all variants...

**Comment by VladislavStefanov** [comment]
The issue should be fixed in the new version of scimono.
