### ISSUE TITLE
Who to get or set the current Tenant?

### ISSUE THREAD

**Issue by tihefrequi** [SAP/scimono#68]
Hello guys, 

is there a default way to set and get something like a tenant?
Or is it possible to set the version of the ApplicationPath ?

Or something like this:

- mydomain.com/{tenant}/scim/User
- mydomain.com/{version}/scim/User

many thanks in advance

**Comment by hborisov** [comment]
Hello,
the library is not tenant aware, we usually implement this functionality on a layer on-top.
As for the versioning, you can achieve it by extending the SCIMApplication class:
@ApplicationPath("scim")
public class DefaultApplication extends SCIMApplication {}

@ApplicationPath("scim/v2")
public class V2Application extends DefaultApplication {}

this way you will have:
mydomain.com/scim/User
and
mydomain.com/scim/{version-which-isv2}/User

**Comment by tihefrequi** [comment]
Thank you very much.
