### ISSUE TITLE
web.xml contains undefined node element "name"

### ISSUE THREAD

**Issue by D033811** [SAP/scimono#89]
Hello guys,
[web.xml](https://github.com/SAP/scimono/blob/master/scimono-examples/simple-server/src/main/webapp/WEB-INF/web.xml) of simple-server application contains the node **name** which is not defined in Java EE or SAP specific application. That prevents a deployment on SAP Netweaver Application Server.

Can you rename the node to **display-name** please?
ThanX Gregor

**Comment by karaimin** [comment]
Fixed
